### ISSUE TITLE
[Question] Can the default value for the client_maxbody_size be changed via nginx.conf?

### ISSUE THREAD

**Issue by dc232** [SteveLTN/https-portal#110]
Hi, I was wondering if it possible to Override the Nginx.conf file config so that the CLIENT_MAX_BODY_SIZE=1M   would then =0  as to avoid a 413 Request Entity Too Large when uploading files back to other docker containers such as WordPress. 
Also, would that be the right approach to this problem or should I just modify default.conf.erb and default.ssl.conf.erb with the line 
    client_max_body_size <%= ENV['CLIENT_MAX_BODY_SIZE'] % || 0 >; 
sorry my ruby is very bad

**Comment by SteveLTN** [comment]
The easiest way is to set `CLIENT_MAX_BODY_SIZE=0` as an environment variable.

```yaml
https-portal:
  environment:
    DOMAINS: 'example.com -> http://upstream'
    CLIENT_MAX_BODY_SIZE: 0
...
```
