### ISSUE TITLE
Not auto renewing

### ISSUE THREAD

**Issue by shuat** [SteveLTN/https-portal#111]
First thanks for creating this service, it is really amazing!

I am using as part of a docker-compose file see below
My issue is that the container did not auto renew.
When I restarted the container, it renewed.

Correct me if I am wrong, but it seems from the docs that this container should automatically setup as cron that auto renews.

```
  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'youtrack.1on1development.com -> http://youtrack, ytviews.bitbean.com -> http://views:9000'
      STAGE: 'production'

    volumes:
      - /var/lib/https-portal:/var/lib/https-portal
      - ./youtrack.1on1development.com.conf.erb:/var/lib/nginx-conf/youtrack.1on1development.com.ssl.conf.erb
```
