### ISSUE TITLE
How to have https-portal expose different port than 80 and 443?

### ISSUE THREAD

**Issue by bhargav3** [SteveLTN/https-portal#124]
I'm trying to expose my container which is using port 8080 on the same port. How can I do that?

The reason being, the container isn't running properly on other ports except 8080.

Here's my `docker-compose.yml` file

```yml
version: "2"

services:
  
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'lora.divumapps.com -> https://appserver:8080'
      STAGE: 'production'    

  loraserver:
    image: loraserver/loraserver
    environment:
      - DB_AUTOMIGRATE=true
      - LOG_NODE_FRAMES=true
      - NET_ID=010203
      - BAND=EU_863_870
      - REDIS_URL=redis://redis:6379
      - GW_MQTT_SERVER=tcp://mosquitto:1883
      - GW_SERVER_JWT_SECRET=verysecret
      - POSTGRES_DSN=postgres://loraserver_ns:loraserver_ns@postgresql_ns/loraserver_ns?sslmode=disable
      - JS_SERVER=http://appserver:8003

  appserver:
    image: loraserver/lora-app-server
    ports:
      - 8080:8080
    environment:
      - DB_AUTOMIGRATE=true
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DSN=postgres://loraserver_as:loraserver_as@postgresql_as/loraserver_as?sslmode=disable
      - MQTT_SERVER=tcp://mosquitto:1883
      - JWT_SECRET=verysecret
      - HTTP_TLS_CERT=/etc/lora-app-server/certs/http.pem
      - HTTP_TLS_KEY=/etc/lora-app-server/certs/http-key.pem
      - AS_PUBLIC_SERVER=appserver:8001

  gatewaybridge:
    ports:
      - 1700:1700/udp
    image: loraserver/lora-gateway-bridge
    environment:
      - MQTT_SERVER=tcp://mosquitto:1883

  postgresql_ns:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=loraserver_ns
      - POSTGRES_USER=loraserver_ns
      - POSTGRES_DB=loraserver_ns

  postgresql_as:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=loraserver_as
      - POSTGRES_USER=loraserver_as
      - POSTGRES_DB=loraserver_as

  redis:
    ports:
      - 6379
    image: redis:4-alpine

  mosquitto:
    ports:
      - 1883:1883
    image: eclipse-mosquitto

```

**Comment by SteveLTN** [comment]
Am I correct?

You have your appserver running at 8080. Now you want to install https-portal, which exposes 80 and 443, and upstreams to your appserver?

If so, for HTTPS-PORTAL to use your appserver as an upstream, you don't need to expose any ports on your appserver container. Just use `DOMAINS: 'lora.divumapps.com -> http://appserver:8080'` (http, not https).

**Comment by bhargav3** [comment]
The container is running on HTTPS on port 8080 and I want to expose on the same port. Like this https://lora.divumapps.com:8080

How can I do that in my compose file? Thanks for helping me out!

**Comment by SteveLTN** [comment]
I see you have a self-signed certificate on port 8080. This is just fine if you plan to use your website only by yourself. If you just trust your own certificate in your browser, you already got what you need. In that case, you don't need HTTPS-PORTAL.

Now if you want others to use your website, you need a proper certificate. 
In that case, HTTPS-PORTAL can put the https on any port you like, but it needs port 80 for ownership verification (Let's Encrypt requires port 80). 
You also need to turn off HTTPS on your own container since the certificate is not trusted by HTTPS-PORTAL. 

Do: 
```
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '8080:443'
    environment:
      DOMAINS: 'lora.divumapps.com -> http://appserver:8080'
      STAGE: 'production'    

appserver:
    image: loraserver/lora-app-server
    # ports: -- Remove this, and put your appserver into HTTP
    #  - 8080:8080
```

**Comment by bhargav3** [comment]
Thanks a lot Weiyan 👍 It worked. Can you add this to docs?

Here's my final `docker-compose.yml` file.

```
version: "2"

services:
  
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '8080:443'
    environment:
      DOMAINS: 'lora.divumapps.com -> https://appserver:8080'
      STAGE: 'production'    

  loraserver:
    image: loraserver/loraserver
    environment:
      - DB_AUTOMIGRATE=true
      - LOG_NODE_FRAMES=true
      - NET_ID=010203
      - BAND=EU_863_870
      - REDIS_URL=redis://redis:6379
      - GW_MQTT_SERVER=tcp://mosquitto:1883
      - GW_SERVER_JWT_SECRET=verysecret
      - POSTGRES_DSN=postgres://loraserver_ns:loraserver_ns@postgresql_ns/loraserver_ns?sslmode=disable
      - JS_SERVER=http://appserver:8003

  appserver:
    image: loraserver/lora-app-server
    ports:
      - 8080
    environment:
      - DB_AUTOMIGRATE=true
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DSN=postgres://loraserver_as:loraserver_as@postgresql_as/loraserver_as?sslmode=disable
      - MQTT_SERVER=tcp://mosquitto:1883
      - JWT_SECRET=verysecret
      - HTTP_TLS_CERT=/etc/lora-app-server/certs/http.pem
      - HTTP_TLS_KEY=/etc/lora-app-server/certs/http-key.pem
      - AS_PUBLIC_SERVER=appserver:8001

  gatewaybridge:
    ports:
      - 1700:1700/udp
    image: loraserver/lora-gateway-bridge
    environment:
      - MQTT_SERVER=tcp://mosquitto:1883

  postgresql_ns:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=loraserver_ns
      - POSTGRES_USER=loraserver_ns
      - POSTGRES_DB=loraserver_ns

  postgresql_as:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=loraserver_as
      - POSTGRES_USER=loraserver_as
      - POSTGRES_DB=loraserver_as

  redis:
    ports:
      - 6379
    image: redis:4-alpine

  mosquitto:
    ports:
      - 1883:1883
    image: eclipse-mosquitto
```
