### ISSUE TITLE
how to specify multiple domain in virtual host when using automatic container discovery?

### ISSUE THREAD

**Issue by ducaale** [SteveLTN/https-portal#129]
```
services:
  a-web-application:
    environment:
      VIRTUAL_HOST: example.com   # and www.example.com
```
also how staging type can be specified ?
