### ISSUE TITLE
Issues with local certificates

### ISSUE THREAD

**Issue by TrueSkrillor** [SteveLTN/https-portal#132]
Hey there,

recently I tested your image in order to protect an application stack with HTTPS. For testing purposes, I set the STAGE to local but I wasn't able to get the reverse proxy to work.

Here is my docker-compose.yml file used for testing purposes:
```yaml
version: "3"
services:
    https-portal:
        image: steveltn/https-portal:latest
        container_name: httpsportal
        restart: always
        ports:
          - "443:443"
          - "80:80"
        volumes:
          - ~/data/https-portal:/var/lib/https-portal
        environment:
          - STAGE=local
          - DOMAINS=pma.example.com -> http://phpmyadmin, pla.example.com -> http://phpldapadmin
        depends_on:
          - "phpldapadmin"
          - "phpmyadmin"
        networks:
          - portal
    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        restart: always
        expose:
        - "80"
        environment:
          - PHPLDAPADMIN_HTTPS=false
        networks:
          - portal
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        expose:
          - "80"
        networks:
          - portal
networks:
    portal:
```

My hosts file is already modified to redirect both, pma.example.com and pla.example.com, to my docker instance. Browsing to these addresses fails with a "Site not available" error. I also noticed the following error during first startup:

>httpsportal     | Generating RSA private key, 2048 bit long modulus
httpsportal     | .........................+++
httpsportal     | ........+++
httpsportal     | e is 65537 (0x010001)
httpsportal     | Self-signing test certificate for pma.example.com
httpsportal     | Signature ok
httpsportal     | subject=CN = pma.example.com
httpsportal     | Getting Private key
httpsportal     | Warning: `chained_cert_path` is deprecated. Use `signed_cert_path` instead in your Nginx config file.
httpsportal     | ln: failed to create symbolic link '/var/lib/https-portal/pma.example.com/local/signed.crt': File exists
httpsportal     | Failed to obtain certs for pma.example.com
httpsportal     | 2018/04/29 07:43:09 [notice] 160#160: signal process started

I hope you can give me a hint what mistake(s) i have done. Thanks!
