### ISSUE TITLE
www forwarding for http://

### ISSUE THREAD

**Issue by randombenj** [SteveLTN/https-portal#140]
I have the problem that when I enable the forwarding from www.example.com to example.com
this works only for https://. 
Is there a way to also enable this for http://, I see in the logs that https-portal receivs a request 
form the browser but sends an empty response.

My configuration:
```yaml
DOMAINS: 'example.com -> http://wordpress, www.example.com => example.com'
```
Any thaughts on how to easily enable forwarding also or http://?

Cheers Benj

**Comment by SteveLTN** [comment]
It is enabled. You should be redirected from `http://www.example.com` to `https://example.com`. I believe the empty response is a 301 redirect.

**Comment by randombenj** [comment]
The problem is that I don't get any response:
```sh
wget http://example.com
```
This works with the 301 permanent moved response to https://example.com

---
```sh
wget https://www.example.com
```
Does not work (certificate issue, guess because there is no certificate for the subdomain with the redirect). Whierdly this works in chrome, but not in firefox dough ...

---
```sh
 wget http://www.example.com
```
Gives an empty response (withaut any headers nor data)
```
HTTP request sent, awaiting response... No data received.
Retrying.
```

**Comment by SteveLTN** [comment]
This is not expected. I will look into it.

**Comment by SteveLTN** [comment]
I set up `test2.steveltn.me` and `test.steveltn.me`. The setting is
```
DOMAINS: 'test2.steveltn.me => test.steveltn.me, test.steveltn.me'
```

Ev

**Comment by randombenj** [comment]
Okay thank you for testing. Things I did were:

- Setting up a CNAME record for `www.example.com`
- Add the redirect to the HTTPS-PORTAL

Any way to test wether `www.exampe.com` is handled by HTTPS-PORTAL?

**Comment by SteveLTN** [comment]
If you remove the redirection part, just have `www.example.com, example.com -> xxxx`, you should see a Nginx welcome screen on `www.example.com`.

**Comment by randombenj** [comment]
I finaly had time to test it and it. So if I remove the redirection and test it again with `www` then there is no response. In the docker logs however https_portal seems to receive the log:
```
https-portal_1  | [01/Aug/2018:16:59:57 +0000] "GET / HTTP/1.1" 444 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" "-"
```
Why is it sending a 444 response?

I assume that the DNS is set up correctly, because using `dig` I can resolve both the website and the `www` subdomain to the same IP address.

Any idea how to change or overwite the 444 response behaviour?

Here you have the docker compose setup for reproducibility:

```yaml
version: '3'

services:
   https-portal:
     image: steveltn/https-portal
     ports:
       - 80:80
       - 443:443
     links:
       - wordpress
     restart: always
     environment:
       DOMAINS: 'example.com -> http://wordpress, www.example.com'
       PRODUCTION: 'true'   
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     # ports:
     #  - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
```
