### ISSUE TITLE
Possibility to specify multiple VIRTUAL_HOST in extern containers

### ISSUE THREAD

**Issue by michiruf** [SteveLTN/https-portal#146]
Because of migration reasons, i have an apache container with multiple sites. It would be awesome to specify multiple `VIRTUAL_HOST` entries. For example:

```
a-multi-port-web-application:
  # ...
  ports:
    - '8080:80'
    - '2222:22'
  environment:
    VIRTUAL_HOST: example.com, www.example.com, mysubproject.example.com
    VIRTUAL_PORT: '8080'
```

It is possible through the compose file of the https-portal container, but I like to separate things as much as possile.

**Comment by SteveLTN** [comment]
Personally I don't currently have time to develop this feature, and that reading other containers' ENVs is getting harder now, so I don't have much faith in auto-discovery any more.

But I think it's good to have and a pull-request is welcome.

**Comment by michiruf** [comment]
Acutally, this feature is already implemented.. sorry about that!
Documenting this would be awesome. You could mentiond the code from above:
```
a-multi-port-web-application:
  # ...
  ports:
    - '8080:80'
    - '2222:22'
  environment:
    VIRTUAL_HOST: example.com, www.example.com, mysubproject.example.com
    VIRTUAL_PORT: 8080
```
And a multiline variant:
```
a-multi-port-web-application:
  # ...
  ports:
    - '8080:80'
    - '2222:22'
  environment:
    VIRTUAL_HOST: '
      example.com,
      www.example.com,
      mysubproject.example.com
    '
    VIRTUAL_PORT: 8080
```

The container is great, thanks!
