### ISSUE TITLE
Use https-portal as an nginx proxy

### ISSUE THREAD

**Issue by mazz** [SteveLTN/https-portal#155]
Here at https://gist.github.com/jswny/83e03537830b0d997924e8f1965d88bc (step 8)
There is a docker-compose.yml which forwards requests at port 80 to port 5000. I would like to forward requests from 443 to 5000..

When I tried swapping-in these settings:
```
image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: '~~redacted~~.com'
    STAGE: 'production'
```

I got a few errors:

```
nginx-server | /opt/certs_manager/lib/nginx.rb:11:in `initialize': Read-only file system @ rb_sysopen - /etc/nginx/conf.d/objectaaron.com.conf (Errno::EROFS)
nginx-server | 	from /opt/certs_manager/lib/nginx.rb:11:in `open'
nginx-server | 	from /opt/certs_manager/lib/nginx.rb:11:in `config_http'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:53:in `block (2 levels) in ensure_signed'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:52:in `each'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:52:in `block in ensure_signed'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:77:in `block in with_lock'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:75:in `open'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:75:in `with_lock'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:51:in `ensure_signed'
nginx-server | 	from /opt/certs_manager/certs_manager.rb:21:in `setup'
nginx-server | 	from /etc/cont-init.d/20-setup:4:in `<main>'
nginx-server | [cont-init.d] 20-setup: exited 1.
nginx-server | [cont-init.d] 30-set-docker-gen-status: executing... 
nginx-server | [cont-init.d] 30-set-docker-gen-status: exited 0.
nginx-server | [cont-init.d] done.
nginx-server | [services.d] starting services
nginx-server | [services.d] done.
nginx-server | Starting crond ...
nginx-server | 2018/09/15 21:36:43 [emerg] 178#178: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | 2018/09/15 21:36:43 [emerg] 178#178: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | 2018/09/15 21:36:43 [emerg] 178#178: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | 2018/09/15 21:36:43 [emerg] 178#178: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | 2018/09/15 21:36:43 [emerg] 178#178: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx-server | 2018/09/15 21:36:43 [emerg] 178#178: still could not bind()
nginx-server | nginx: [emerg] still could not bind()
nginx-server | [cont-finish.d] executing container finish scripts...
nginx-server | [cont-finish.d] done.
nginx-server | [s6-finish] syncing disks.
nginx-server | [s6-finish] sending all processes the TERM signal.
nginx-server | [s6-finish] sending all processes the KILL signal and exiting.
```

For the first error, how is that https-portal maintains a write file system, for instance?

Not sure why I'm getting the address already is use issue.

Any help would be appreciated.

Michael

**Comment by SteveLTN** [comment]
Looks like some other process is taking port 80 on your computer.

**Comment by mazz** [comment]
the port already in use has something to do with the nginx-network but I'm not sure what.

Here is my latest iteration of the docker-compose.yml(same issue though)

```
version: "3"
services:
  server:
    image: steveltn/https-portal:1
    container_name: nginx-server
    ports:
      - '80:80'
      - '443:443'
    environment:
      STAGE: local
      DOMAINS: "olivetree"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
```

**Comment by SteveLTN** [comment]
Doesn't seem to have problems in the compose file. The port 80 is mostly taken by other processes outside of docker, on in another compose.

**Comment by SteveLTN** [comment]
Interesting. I'll have a look tonight.

Just noticed you mounted `/etc/nginx/conf.d` as read-only. Do you want to supply your own nginx config instead of using the environment variables? If so, you should remove `DOMAINS` env. Otherwise, you need to mount without `ro`. 

And also may I see what's inside `conf.d` as well?

**Comment by SteveLTN** [comment]
After some look, I think the problem is: HTTPS-PORTAL is not a drop-in replacement of Nginx. You are giving it your old nginx configuration file, which wouldn't work without modification.

However, what you can do, is to remove
```
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
```
entirely, and configure HTTPS-PORTAL through environment variables:
```
    environment:
      STAGE: local
      DOMAINS: "olivetree -> http://olivetree-server:5000/"
```

I might have missed something. If it doesn't work, please check out the docs.

**Comment by mazz** [comment]
@SteveLTN thanks, your fix worked in 'local' mode. I will try it on Digital Ocean with a real domain name.

**Comment by mazz** [comment]
It works!

here is the final `docker-compose.yml`

```
version: "3"
services:
  server:
    image: steveltn/https-portal:1
    container_name: nginx-server
    ports:
      - '80:80'
      - '443:443'
    environment:
      #STAGE: local
      STAGE: 'production'
      DOMAINS: "****.com -> http://olivetree-server:5000/"
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
```
