### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by dmuth** [SteveLTN/https-portal#158]
Hi,

This app looks cool--in fact, it's exactly what I've been looking for to automate my LetsEncrypt certificate generation!  I am having some challenges trying to get it to work, though.

My plan is to start by listening on ports 8080 and 8443 so that I can run this in parallel with my existing setup (Nginx listening on ports 80 and 443 proxying traffic to underlying Docker containers).  However, when I try loading https://www.septastats.com:8443/ in Chrome, I get `ERR_SPDY_PROTOCOL_ERROR`.  When I try it via curl, I get this:

`curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)`

This is the Docker Compose configuration I am using:
```
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8080:80'
      - '8443:443'
    restart: always
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'septastats.com -> http://localhost:8001'
      STAGE: 'local'
```

...and my website is set up in Docker, listening on port 8081:

```
# curl -I localhost:8001                                                                                                                                                                                                                                      
HTTP/1.1 200 OK
Server: nginx/1.15.2
Date: Fri, 21 Sep 2018 01:40:06 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 10487
Connection: keep-alive
X-Powered-By: PHP/7.2.8
```

Do you have any suggestions?  I'll leave https://www.septastats.com:8443/  running in case you'd like to hit it yourself with curl.  Is there anything you need from me?

Thanks,

-- Doug

**Comment by SteveLTN** [comment]
You wrote `DOMAINS: 'septastats.com -> http://localhost:8001'`. But what is `localhost` in Docker? Unless you configured it explicitly, the `localhost` in the Docker container means the container itself. You should probably look into links to your existing containers.

Another note, Let's Encrypt requires port 80 to verify the ownership of the domain. That means HTTPS-PORTAL has to listen to 80 when getting the certificate. You can proxy `/.well-known/acme-challenge/` on port 80 to HTTPS-PORTAL to work it around if you have something else on 80.

**Comment by dmuth** [comment]
> But what is localhost in Docker? 

Ohhhh... you're right.  That hadn't even occurred to me.  Okay, so that clearly won't work. :-)

As per your suggestion for trying links, the containers I want to proxy HTTPS for are handled by other `docker-compose.yml` files, so I tried out `external_links` for the first time.  This is what my `docker-compose.yml` file now looks like:

```
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8080:80'
      - '8443:443'
    restart: always
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    external_links:
      - septa-stats_web_1:septastats
    environment:
      DOMAINS: 'septastats.com -> http://septastats:8001'
      STAGE: 'local'
```

And I verified that I got the right container name:
```
# docker ps |grep septa |grep web
4037c6041285        nginx:alpine                                                            "nginx -g 'daemon of…"   4 hours ago         Up 24 minutes       0.0.0.0:8001->80/tcp                          septa-stats_web_1
```

Unfortunately, name resolution didn't seem to work:
```
https-portal_1  | 2018/09/24 01:59:33 [emerg] 146#146: host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | nginx: [emerg] host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | 2018/09/24 01:59:33 [emerg] 147#147: host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | nginx: [emerg] host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | 2018/09/24 01:59:33 [emerg] 149#149: host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | nginx: [emerg] host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | Signing skipped for septastats.com, it expires at 90 days from now.
https-portal_1  | 2018/09/24 01:59:33 [emerg] 151#151: host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | nginx: [emerg] host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | [cont-init.d] 20-setup: exited 0.
https-portal_1  | [cont-init.d] 30-set-docker-gen-status: executing... 
https-portal_1  | [cont-init.d] 30-set-docker-gen-status: exited 0.
https-portal_1  | [cont-init.d] done.
https-portal_1  | [services.d] starting services
https-portal_1  | [services.d] done.
https-portal_1  | Starting crond ...
https-portal_1  | 2018/09/24 01:59:34 [emerg] 178#178: host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | nginx: [emerg] host not found in upstream "septastats" in /etc/nginx/conf.d/septastats.com.ssl.conf:28
https-portal_1  | [cont-finish.d] executing container finish scripts...
https-portal_1  | [cont-finish.d] done.
https-portal_1  | [s6-finish] syncing disks.
https-portal_1  | [s6-finish] sending all processes the TERM signal.
https-portal_1  | [s6-finish] sending all processes the KILL signal and exiting.
```

I am running a fairly recent version of Docker: `Docker version 18.06.1-ce, build e68fc7a`

Any suggestions?

Thanks,

-- Doug

**Comment by dmuth** [comment]
Ended up answering my own question--a Google Search explained that I needed to put this container into the network of the other container:

```
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8080:80'
      - '8443:443'
    restart: always
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    networks:
      - septa-stats_default
    external_links:
      - "septa-stats_web_1:septastats"
    environment:
      DOMAINS: 'septastats.com -> http://septastats:8001'
      STAGE: 'local'

networks:
  septa-stats_default:
    external: true
```

Still doesn't work, however:
```
$ curl -k https://www.septastats.com:8443
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

It also brings up the additional question: is it possible for https-portal to proxy multiple webservers if they are in different networks? (And I do prefer to keep my different projects on different networks in Docker...)

Thanks,

-- Doug
