### ISSUE TITLE
Service discovery seems to be not working

### ISSUE THREAD

**Issue by blackandred** [SteveLTN/https-portal#160]
Hi,

I set up a gateway with https-portal image and tagged services with environment variables.

Image version: steveltn/https-portal:1 (currently it's 1.4.2)

```yaml
environment:
            # gateway configuration
            - VIRTUAL_HOST=health.anarchista.net${DOMAIN_SUFFIX}
            - VIRTUAL_PORT=8000
```

```yaml
gateway:
        image: steveltn/https-portal:1
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

And I got:

```bash
gateway_1             | 2018/09/26 20:32:07 Generated '/var/run/domains' from 18 containers
gateway_1             | 2018/09/26 20:32:07 Running 'reconfig'
gateway_1             | 2018/09/26 20:32:08 Error running notify command: reconfig, exit status 1
gateway_1             | 2018/09/26 20:32:08 [reconfig]: Error: Invalid descriptor git.anarchista.net.localhost -> 
gateway_1             | 2018/09/26 20:32:08 [reconfig]: http://anarchista_net_gogs_1:80
gateway_1             | 2018/09/26 20:32:08 [reconfig]: /opt/certs_manager/models/domain.rb:72:in `name': undefined method `[]' for nil:NilClass (NoMethodError)
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/models/domain.rb:39:in `dir'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/models/domain.rb:121:in `create_dir'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/models/domain.rb:10:in `initialize'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/lib/na_config.rb:50:in `new'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/lib/na_config.rb:50:in `block in parse'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/lib/na_config.rb:49:in `map'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/lib/na_config.rb:49:in `parse'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/lib/na_config.rb:40:in `auto_discovered_domains'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /opt/certs_manager/certs_manager.rb:45:in `reconfig'
gateway_1             | 2018/09/26 20:32:08 [reconfig]: 	from /bin/reconfig:4:in `<main>'
gateway_1             | 2018/09/26 20:32:08 Watching docker events
gateway_1             | 2018/09/26 20:32:08 Contents of /var/run/domains did not change. Skipping notification 'reconfig'

```

**Comment by blackandred** [comment]
```
$ docker --version
Docker version 18.06.1-ce, build e68fc7a215

$ docker-compose --version
docker-compose version 1.22.0, build unknown
```

**Comment by blackandred** [comment]
Works on `steveltn/https-portal:1.3.0`

**Comment by SteveLTN** [comment]
Hi, could you try again with the newly release 1.4.3? The regex was refactored and underscore was somehow left out. Now it is fixed and added to the test :-)

**Comment by blackandred** [comment]
Thanks :)

**Comment by WebDucer** [comment]
I have following setup:

```yml
version: '3'
services:
    https_proxy:
        image: steveltn/https-portal:1.3.0
        container_name: ci-https-proxy
        ports:
            - "80:80"
            - "443:443"
        environment:
            STAGE: ${ENV_STAGE}
            CLIENT_MAX_BODY_SIZE: 10G
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ci_proxy_certs:/var/lib/https-portal
    nextcloud:
        image: wonderfall/nextcloud:14
        container_name: our-nextcloud
        hostname: cloud.${ENV_DOMAIN_CLOUD}
        depends_on:
            - https_proxy
            - nextcloud_db
            - nextcloud_redis
        environment:
            VIRTUAL_HOST: "cloud.${ENV_DOMAIN_CLOUD} -> http://our-nextcloud:8888"
            UPLOAD_MAX_SIZE: 10G
            CRON_PERIOD: 15m
            ADMIN_USER: "Admin"
            ADMIN_PASSWORD: "..."
            DOMAIN: cloud.${ENV_DOMAIN_CLOUD}
            DB_TYPE: "mysql"
            DB_NAME: "nextcloud"
            DB_USER: "nextcloud"
            DB_PASSWORD: "..."
            DB_HOST: "nextcloud_db"
        volumes:
            - nextcloud_data:/data
            - nextcloud_config:/config
            - nextcloud_apps:/apps2
            - nextcloud_themes:/nextcloud/themes
            - nexcloud_session:/php/session
...
```

`ENV_DOMAIN_CLOUD` is set to `recy-systems.com`.
