### ISSUE TITLE
Default and default redirect

### ISSUE THREAD

**Issue by LorenzHenk** [SteveLTN/https-portal#165]
Is there any way to define a default action? 
When no domain listed in 'DOMAINS' matches, I'd like to show a custom error page or redirect to my main website.
Maybe you can use wildcards, like for example:
```
https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  environment:
    DOMAINS: 'example.com -> http://dockerhost:8080, * => example.com'
```
