### ISSUE TITLE
Docker HTTPS-Portal and Sismics

### ISSUE THREAD

**Issue by petrk94** [SteveLTN/https-portal#168]
Hello,

Im facing currently the issue, that I dont get Sismics and HTTPS-Portal work together.
I have created a dockerfile with HTTPS-Portal and Sismics inside.
But Sismics doesnt react on the HTTPS certificate and try to get loaded something like a hard coded code.
Sismics developer say its a https-portal issue.

Might you can help?
Thanks

Related issue on Sismics Side
https://github.com/sismics/docs/issues/251

**Comment by SteveLTN** [comment]
Sorry for the fuzzy typing, I am traveling without my computer. Typing
on the phone.

you should do this:

DOMAINS: your site.com => http://sysmics:80

Hello,

**Comment by petrk94** [comment]
@SteveLTN 
Hello, thanks for your response.
I made that change in the docker file and run it again, but it doesnt work. In the address bar I get this instead:
"https://http//sysmics:80/"

The https is coming from https-portal, so far its fine, but the http// where its coming from?

Sismics has this command to run 
docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='http://[your-docker-host-ip]:8100' -p 8100:8080 -v sismics_docs_latest:/data sismics/docs:latest

But there is no explaination which is responsible for what.

This is my current docker-compose.yml file

```
https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - sismics
  environment:
    DOMAINS: 'sub.domain.net => http://sismics:80'
    STAGE: 'production'

sismics:
  image: sismics/docs

```

I hope you can help me.
Thanks

**Comment by SteveLTN** [comment]
This is probably a bug. I will have a look when I get back home on Nov 8.

 Though according to the test here
https://github.com/SteveLTN/https-portal/blob/master/spec/models/domain_spec.rb
It shouldn’t behave like that...

**Comment by petrk94** [comment]
@SteveLTN 
Im looking for your response :)

**Comment by petrk94** [comment]
@SteveLTN 
could you took a look on it?

**Comment by SteveLTN** [comment]
Hi, 

After some debugging, I found the problem lies in your configuration. You should use single array `->` instead of the fat arrow `=>`. According to the [documentation](https://github.com/SteveLTN/https-portal#redirections), double arrow means redirection, not proxy.

**Comment by SteveLTN** [comment]
```
DOMAINS: local.steveltn.me -> http://sismics
```

**Comment by petrk94** [comment]
@SteveLTN 
Hello, Sismics developer doesnt seems to be very helpful at this :( 

I have it changed as you wrote ( `->` instead of `=>`).
This is my current dockerfile

```
cat docker-compose.yml


https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - sismics
  environment:
    DOMAINS: 'sub.domain.net -> http://sismics:80'
    STAGE: 'production'

sismics:
  image: sismics/docs
```

It working at least so far, that the subdomain get opened on HTTPS and certificate is valid, but I get a 

> 502 Bad Gateway
> nginx

As response. Do you know how to solve it?
Thanks

**Comment by petrk94** [comment]
Here on the sismics/docs repository is this code:
https://github.com/sismics/docs#install-with-docker

`docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='http://[your-docker-host-ip]:8100' -p 8100:8080 -v sismics_docs_latest:/data sismics/docs:latest
`

This works without problem, but not with https, only http

**Comment by SteveLTN** [comment]
Unfortunately I haven't heard of Sismics before and don't know how to use it. But I'd say put sismics (that `docker run` command) into docker-compose first, make it working with http only but in docker-compose. Then try to add HTTPS-PORTAL on top of it.

**Comment by petrk94** [comment]
@SteveLTN 
So you mean this way?

```
sismics:
  docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='http://[your-docker-host-ip]:8100' -p 8100:8080 -v sismics_docs_latest:/data sismics/docs:latest

https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - sismics
  environment:
    DOMAINS: 'sub.domain.net -> http://sismics:80'
    STAGE: 'production'


```

**Comment by SteveLTN** [comment]
No. Write a proper compose file that is equivalent to what the docker run
command.

**Comment by petrk94** [comment]
@SteveLTN 
Unfortunately I have not really an idea about how to create such a file. I will ask sismics and come here back again.

**Comment by petrk94** [comment]
@SteveLTN 
Due I dont got a response from sismics/docs developer, I had to find a own solution for this.
Here is the docker-compose.yml file which work without problems:

`docker run --rm --name sismics_docs_latest -d -e DOCS_BASE_URL='http://[your-docker-host-ip]:8100' -p 8100:8080 -v sismics_docs_latest:/data sismics/docs:latest
`

docker 
    -d = Run container in background and print container ID
    -e = Set environment variables
    -p = Ports
    -v = Bind mount a volume

```
sismics:
    image: sismics/docs
    ports:
        - "8100:8080"
    environment:
        - DOCS_BASE_URL='http://[your-docker-host-ip]:8100'
    volumes:
        - sismics_docs_latest/data
```

This code is working on my server. I hope you can help me here.
Thanks

**Comment by SteveLTN** [comment]
This works for me.
```yaml
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - sismics
    environment:
      DOMAINS: local.steveltn.me -> http://sismics:8080
      STAGE: 'local'

  sismics:
      image: sismics/docs
      ports:
          - "8100:8080"
      environment:
          - DOCS_BASE_URL='http://[your-docker-host-ip]:8100'
      volumes:
          - sismics_docs_latest/data
```
