### ISSUE TITLE
https-portal does not restart automatically

### ISSUE THREAD

**Issue by Eggham** [SteveLTN/https-portal#172]
Hi,

Love your project! 

I set https-portal to be automatically restarted via docker compose. However, it does not survive host restart.

My docker-compose.yml is as follows:
```
version: '3.3'

services:
   https-portal:
      image: steveltn/https-portal
      ports:
        - 80:80
        - 443:443
      links:
        - wordpress
      restart: always
      environment:
        - "DOMAINS=www.example.com -> http://wordpress"
        - "PRODUCTION=true"

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
     volumes:
       - ./website:/var/www/html
volumes:
db_data:
```

The container https-portal showed State of `Exit 0` upon host machine restart. I have to manually restart the container by `docker-compose restart`.

Would you please kindly show how to address the problem?
