### ISSUE TITLE
cert renew is blocked when global access restriction is used

### ISSUE THREAD

**Issue by prilka** [SteveLTN/https-portal#189]
with an active global access restriction the request from the LE-Server is blocked too.

```yml
  https-portal:
    image: steveltn/https-portal:latest
    environment:
      ACCESS_RESTRICTION: "x.x.x.x"
```

```
https-portal_1     | 2019/03/29 11:17:39 [error] 174#174: *2 access forbidden by rule, client: 66.133.109.36, server: mydomain.com, request: "GET /.well-known/acme-challenge/pAtp5k5w2i_SefxaYxyJevMz7Y-RoWWDgLrGqU2WAQc HTTP/1.1", host: "mydomain.com"
```
