### ISSUE TITLE
404 - Not found when go to site

### ISSUE THREAD

**Issue by dingo-d** [SteveLTN/https-portal#193]
My `docker-compose.yaml` file looks like this:

```yaml
version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: wp-docker-db
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wordpress-app
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    ports:
      - "33066:3306"

  web:
    image: wordpress:5.1.1-fpm
    container_name: wp-docker-web
    depends_on:
      - db
    restart: always
    volumes:
      - ./bin/php.ini:/usr/local/etc/php/conf.d/local.ini
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp

  https-portal:
    image: steveltn/https-portal:latest
    container_name: wp-docker-ssl
    depends_on:
      - web
    ports:
      - 8010:80
      - 442:443
    restart: always
    volumes:
      - ./logs:/var/log/nginx
    environment:
      DOMAINS: 'wp.mysite.test -> http://web:80 #local'
      STAGE: 'local'
      CLIENT_MAX_BODY_SIZE: 64M
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wordpress-app


volumes:
  db_data: {}
```

When I go to `https://wp.mysite.test` first I get `404 - Not Found` screen, and the Chrome says not secure.

The `docker ps --all` gives me 3 containers

```bash
CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS              PORTS                                        NAMES
7ae0ea399fe6        steveltn/https-portal:latest   "/init"                  About a minute ago   Up About a minute   0.0.0.0:8010->80/tcp, 0.0.0.0:442->443/tcp   wp-docker-ssl
f5b6eb62a7ba        wordpress:5.1.1-fpm            "docker-entrypoint.s…"   About a minute ago   Up About a minute   9000/tcp                                     wp-docker-web
929ced39d889        mysql:5.7                      "docker-entrypoint.s…"   8 minutes ago        Up 8 minutes        33060/tcp, 0.0.0.0:33066->3306/tcp           wp-docker-db
```

I can `exec` to every container. `docker exec -it wp-docker-ssl /bin/bash` running `nginx -t` says everything is ok

```bash
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

php works, db is showing up when I connect to it using sequel pro. 

What am I missing?
