### ISSUE TITLE
remote-ip not passing through

### ISSUE THREAD

**Issue by brainlid** [SteveLTN/https-portal#194]
## Background

- https-portal 1.7.1
- configuration via docker-compose with wordpress
- Wordpress logs show all traffic as from IP 172.18.0.4

## Problem

I'm using a wordpress plugin that blocks an IP after X failed attempts. All logins appear to be from the same IP.

I got a shell into the container and saw that the `/var/lib/nginx-conf/` files appear to be correct using `x-real-ip`. I'm not overriding any of the config files.

How can I ensure the client's IP address is being passed through to the wordpress instance?

**Comment by wiserain** [comment]
It's been long lasting problem of docker network. https://github.com/moby/moby/issues/15086

**Comment by SteveLTN** [comment]
As @wiserain mentioned, it is a problem of Docker. Use host network, and make sure your compose is not in a virtual machine. It does get the correct user address.

**Comment by brainlid** [comment]
Thanks @SteveLTN & @wiserain. I've been looking into this problem and have been confused by the history of it. I find information that may be out of date, or other solutions that may only work in newer versions of Docker and Docker Compose.

I'm using a docker-compose file directly on an AWS EC2 instance. I think I may need to update some underlying software versions, but I'm not sure.

Do you have any samples of a working compose file that uses the host network? I don't want my mysql instance to be addressable directly from the web though.

```
$ docker --version
Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136

$ docker-compose -v
docker-compose version 1.21.2, build a133471
```

Here's my current attempt that isn't working: (The IPs still come through like `172.19.0.4`)

```yaml
version: '3.6'

services:
  https-portal:
    container_name: ${CONTAINER_HTTPS_PORTAL}
    image: steveltn/https-portal:1.7.1
    ports:
      - '80:80'
    #  - target: 80
    #    published: 80
    #    protocol: tcp
    #    mode: host
    #  - '443:443'
      - target: 443
        published: 443
        protocol: tcp
        mode: host

    #links:
    #  - wordpress
    #networks:
    #  - service
    depends_on:
      - wordpress
    restart: unless-stopped
    environment:
      # Forward wordpress.example.com to the WordPress container.
      # You can set up multiple domains at once. (comma separated)
      # NOTE: redirections are done using "=>"
      DOMAINS: 'wbscourse.com -> http://wordpress, www.wbscourse.com => wbscourse.com'
      #DOMAINS: 'wbscourse.com -> http://127.0.0.1:8080, www.wbscourse.com => wbscourse.com'

      # Using staging server by default, for there is a rate limit on production.
      # Set to 'production' to use Let's Encrypt production server.
      STAGE: 'production'
      # FORCE_RENEW: 'true'
      # Changes the file upload size allowed in nginx
      CLIENT_MAX_BODY_SIZE: 100M

  wordpress:
    container_name: ${CONTAINER_WP_NAME}
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    # ports:
    #   - 127.0.0.1:80:80 # change ip if required
    #ports:
    #  - 127.0.0.1:8080:80
    volumes:
      - ${WP_UPLOAD_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini:ro
      # - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # - ./wp-app:/var/www/html # Full wordpress project
      - ${WP_CORE}:/var/www/html
      - ${WP_CONTENT}:/var/www/html/wp-content
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      #WORDPRESS_DB_HOST: db-wbs  #127.0.0.1:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      # VIRTUAL_HOST: ${DOMAINS}
      # LETSENCRYPT_HOST: ${DOMAINS}
      # LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: ${CONTAINER_DB_NAME}
    image: mysql:8.0.11 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    #ports:
    #  - 127.0.0.1:3306:3306 # change ip if required
    ports:
      - 127.0.0.1:3306:3306 # change ip if required
      #- target: 3306
      #  published: 3306
      #  protocol: tcp
      #  mode: host

    volumes:
      - ${MYSQL_DB_PATH}:/var/lib/mysql
      - ${MYSQL_EXPORT_DIR}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

#networks:
#    default:
#       external:
#         name: host
#         #name: ${NETWORK}

#    service:
#       external:
#         name: host
```

**Comment by SteveLTN** [comment]
Hi, @brainlid 

This is the compose file I'm using:

```
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1.7.1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: test.steveltn.me -> http://echo:8080
      STAGE: 'production'
    networks: 
      - default

  echo:
    image: brndnmtthws/nginx-echo-headers
    networks:
      - default

networks:
  default:
    driver: bridge
```

Here I use `brndnmtthws/nginx-echo-headers` to just list all request headers in the webpage.
You can test it out on https://test.steveltn.me/.
I simply opened a DigitalOcean machine and installed Docker & docker-compose. Apparently both `driver: bridge` and `driver: host` works for me.

```sh
❯ docker version                                                                                       
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

❯ docker-compose version                                                                               
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Comment by brainlid** [comment]
@SteveLTN, thanks for providing some guidance. Here's what I'm currently seeing. 

docker-compose.yml file

```yaml
version: '3'

services:
  https-portal:
    container_name: ${CONTAINER_HTTPS_PORTAL}
    image: steveltn/https-portal:1.7.1
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
    depends_on:
      - wordpress
    restart: unless-stopped
    environment:
      # Forward wordpress.example.com to the WordPress container.
      # You can set up multiple domains at once. (comma separated)
      # NOTE: redirections are done using "=>"
      DOMAINS: 'mysite.com -> http://wordpress, www.mysite.com => mysite.com'

      # Using staging server by default, for there is a rate limit on production.
      # Set to 'production' to use Let's Encrypt production server.
      STAGE: 'production'
      # FORCE_RENEW: 'true'
      # Changes the file upload size allowed in nginx
      CLIENT_MAX_BODY_SIZE: 100M

  wordpress:
    container_name: ${CONTAINER_WP_NAME}
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    volumes:
      - ${WP_UPLOAD_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini:ro
      # - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # - ./wp-app:/var/www/html # Full wordpress project
      - ${WP_CORE}:/var/www/html
      - ${WP_CONTENT}:/var/www/html/wp-content
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      #WORDPRESS_DB_HOST: db-wbs  #127.0.0.1:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      # VIRTUAL_HOST: ${DOMAINS}
      # LETSENCRYPT_HOST: ${DOMAINS}
      # LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - db
    networks:
      - default
    restart: unless-stopped

  db:
    container_name: ${CONTAINER_DB_NAME}
    image: mysql:8.0.11 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    volumes:
      - ${MYSQL_DB_PATH}:/var/lib/mysql
      - ${MYSQL_EXPORT_DIR}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
```

I rebuilt the containers and watched the logs.

```
docker-compose down
docker-compose up -d
docker-compose logs -f
```

It runs fine but the logs show all requests still coming in like `172.26.0.4`.

When I tear it all down and rebuild using the following network settings:

```yaml
networks:
  default:
    driver: host
```

It fails to create with docker-compose.

```
$ docker-compose down
$ docker-compose up -d
Creating network "mysite_network_default" with driver "host"
ERROR: only one instance of "host" network is allowed
```

The only thing I have left to try is update the versions of docker.

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Mar  4 21:25:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Mar  4 21:26:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

I'm not sure how to yet.
