### ISSUE TITLE
502 Bad Gateway when running with multiple compose files with docker stack deploy

### ISSUE THREAD

**Issue by kissgyorgy** [SteveLTN/https-portal#202]
I wanted to make the following structure for my project from docker-compose files:
- `base.yml`
- `prod.yml` which overrides base.yml with prod-specific volumes and environment variables
- `local.yml` same for local testing and development

When I run the command `docker stack deploy -c base.yml -c local.yml portal`, a wrong upstream IP address will be used in https-portal but I cannot see where and why:

```
2019/06/30 07:46:16 [error] 209#209: *4 upstream prematurely closed connection while reading response header from upstream, client: 10.255.0.2, server: walkman.local, request: "GET /web/ HTTP/2.0", upstream: "http://10.0.7.2:8069/web/", host: "walkman.local", referrer: "https://walkman.local/"
2019/06/30 07:46:16 [error] 209#209: *4 upstream prematurely closed connection while reading response header from upstream, client: 10.255.0.2, server: walkman.local, request: "GET /favicon.ico HTTP/2.0", upstream: "http://10.0.7.2:8069/favicon.ico", host: "walkman.local", referrer: "https://walkman.local/web/"
```
The 10.0.7.2 IP address doesn't exist in the deployed stack:
```bash
$ for cid in $containers; do docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}, {{end}}' $cid; done
10.255.0.39, 10.0.7.8, 
10.0.7.6, 
10.0.7.3, 
```
The first line is for https-portal. The correct ip address always seems to be 1 bit higher (10.0.7.3 in this case).

Here is the `base.yml` compose file:
```
version: '3.7'
services:
  https-portal:
    image: steveltn/https-portal:1
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 300s
    ports:
      - "80:80"
      - "443:443"

  odoo:
    image: odoo:12.0
    deploy:
      restart_policy:
        condition: any
        delay: 15s
        window: 300s
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    deploy:
      restart_policy:
        condition: any
        delay: 30s
        window: 600s
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
      # this is the initdb recommended directory: https://hub.docker.com/_/postgres
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  odoo-data:
  postgres-data:
  https-portal-data:
```
Here is my `local.yml` file:
```
version: '3.7'
services:
  https-portal:
    volumes:
      - ./data/https-portal:/var/lib/https-portal
    environment:
      # HOSTNAME environment variable is NOT EXPORTED by default either in bash!!
      # see: https://github.com/docker/compose/issues/4282
      DOMAINS: "${HOSTNAME}.local -> http://odoo:8069"
      STAGE: "local"

  odoo:
    volumes:
      - ./data/odoo:/var/lib/odoo

  postgres:
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
```
I tried to exec into the https-portal container and reload nginx, but it did not help.
Also tried to update the stack after deploy with:
`docker stack deploy -c docker-stack-base.yml -c docker-stack-local.yml mystack` did not help.
Neither running `docker service update --force mystack_https-portal`.

When I put the config in one file, everything works fine. I'm not sure if this is a https-portal issue with the `DOMAINS` environment parsing or something, an nginx issue with DNS lookups or a docker swarm DNS server issue. I don't even know where that IP address is coming from.

I noticed that there is an https-portal instance restarted when I start the stack:
```
$ docker stack ps mystack
ID                  NAME                     IMAGE                     NODE                DESIRED STATE       CURRENT STATE                 ERROR               PORTS
q1c5p8ufpf5q        mystack_https-portal.1   steveltn/https-portal:1   ryzenable           Running             Running about a minute ago                        
vk13e1jzmtxq        mystack_postgres.1       postgres:10               ryzenable           Running             Running about a minute ago                        
he5fgocrxknz        mystack_odoo.1           odoo:12.0                 ryzenable           Running             Running about a minute ago                        
o03xrf3rot25        mystack_https-portal.1   steveltn/https-portal:1   ryzenable           Shutdown            Complete about a minute ago                       
```

I can reproduce this every time.
