### ISSUE TITLE
 How to move certificates to another server? 

### ISSUE THREAD

**Issue by heyt0ny** [SteveLTN/https-portal#206]
Hello! 

Thanks for an awesome tool. 

Recently I faced the problem to move the website to another server. I copied the certificates from `/var/lib/https-portal` and pasted them to new `host`. However from the all files only one `/var/lib/https-portal/my-domain.com/production/chained.crt` is not copied. So when I'm running the docker on new host I get `cannot load certificate "/var/lib/https-portal/my-domain.com/production/chained.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/lib/https-portal/my-domain.com/production/chained.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

Is there any way to copy certs to new server ? (as I hit the limit  and cannot reissue certs on new server)

**Comment by SteveLTN** [comment]
`signed.crt` is already chained. `chained.crt` is just a symlink to maintain the compatibility with old configurations. You can just modify you nginx config to use `signed.crt` or duplicate/symlink `signed.crt`.

**Comment by heyt0ny** [comment]
Thank you. Sorry I don't totally understand, by `modify you nginx config to use signed.crt or duplicate/symlink signed.crt.` What do you mean?

I have the following dc
```
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
    - /data/ssl_certs:/var/lib/https-portal
    env_file:
      - .env
    environment:
      DOMAINS: 'dotaleaker.com => www.dotaleaker.com, www.dotaleaker.com -> http://web:12134'
      STAGE: 'staging'
      FORCE_RENEW: 'false'

```

And in `data/ssl_certs/instamer.com/production/` only have `signed.crt`
