### ISSUE TITLE
Only works locally

### ISSUE THREAD

**Issue by AdnanHodzic** [SteveLTN/https-portal#211]
Hi,

I'm big fan of this project, and have been using it for couple of years now. However, I wanted to update my docker-compose file, and I have a weird problem. 

When deployed locally everything works fine, I'm using `STAGE: 'local'` and I set `127.0.0.1 test.foolcontrol.org` as part of my `/etc/hosts/ file. 

However, when I deploy this same docker-compose file on AWS with only change being `STAGE: 'staging', I'll end up with:

```
This site can’t be reached
test.foolcontrol.org took too long to respond.

Try:
Checking the connection
Checking the proxy and the firewall

ERR_CONNECTION_TIMED_OUT
```

Hence, I'm very confused with what the problem is. Any idea on what I'm doing wrong?

`docker-compose.yml` contents:

```
version: '3.1'

services:

  https-portal:
    image: steveltn/https-portal
    container_name: https
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - '80:80'
      - '443:443'
    environment:
      CLIENT_MAX_BODY_SIZE: '100M'
      GZIP: 'on'
      DOMAINS: 'test.foolcontrol.org -> http://wordpress:80'
      STAGE: 'local'
    links:
      - wordpress
    restart: unless-stopped
    networks:
      - wp

  wordpress:
    links:
      - db:mysql
    image: wordpress
    container_name: wp
    volumes:
      - ./wordpress:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_NAME: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'change-M3'
      WORDPRESS_DB_HOST: 'db'
      MYSQL_PORT_3306_TCP: '3306'
    restart: unless-stopped
    networks:
      - wp

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./wp-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'change-M3'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'change-M3'
    restart: unless-stopped
    networks:
      - wp

networks:
  wp:
    driver: bridge
```

Thanks!
