### ISSUE TITLE
[Suggestion] Make auto-renewal more stable

### ISSUE THREAD

**Issue by vespakoen** [SteveLTN/https-portal#219]
I have had renewal issues since the beginning of using this project.
Today my certificates expired again and I decided to get to the bottom of this issue.

The last comment in this issue (https://github.com/SteveLTN/https-portal/issues/197) pointed me in the right direction and I noticed that /etc/cron_env.sh had a `export ""` line in it, which is invalid.

I then noticed that I was using YAML's multiline support to list my domain mappings over multiple lines like this:

```yaml
https-portal:
  image: steveltn/https-portal:latest
  restart: always
  ports:
    - 80:80
    - 443:443
  links:
    - dl
    - dlbeta
    - ci
  volumes:
    - /data/ssl_certs:/var/lib/https-portal
  environment:
    DOMAINS: >
      dl.bla.com -> http://dl,
      dlbeta.bla.com -> http://dlbeta,
      ci.bla.com -> http://ci
    STAGE: production
    WEBSOCKET: "true"
    RESOLVER: 127.0.0.11 valid=60s
```

This produces the empty export line somehow.

Changing it to a single line fixes this issue.

I guess this might be caused by the introduced newlines, and I guess it could be fixed by trimming / stripping them out.
