### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by heyt0ny** [SteveLTN/https-portal#226]
Hi! I'am can't figure out where is the problem.

My proxy dc:
```
version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1.10.1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
    - /data/ssl_certs:/var/lib/https-portal
    env_file:
      - .env
    environment:
      DOMAINS: 'mydomain.com => www.mydomain.com, www.mydomain.com -> http://127.0.0.1:12135'

      STAGE: 'production'
      FORCE_RENEW: 'false'
```

My main dc 
```
version: '3'
services:
  web:
    build: './service_web'
    container_name: website
    ports:
      - "12135:12135"
    expose:
      - "12135"
    volumes:
      - bla bla
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - redis
      - api
   command: >
       bash -c "go run /app/main.go"
  api:
    build: './service_api'
    container_name: api
    env_file:
      - .env
    volumes:
     - bla black
    expose:
      - "5215"
    ports:
      - "5215:5215"
    working_dir: /app
    depends_on:
      - redis
   command: >
      bash -c "gunicorn --daemon -b 0.0.0.0:5215 server:app --workers=4 && python3 run.py"
  redis:
    image: "redis:latest"
    container_name: redis
    volumes:
      - ${DUMP_DIR}/redis_docker:/data
    env_file:
      - .env
    expose:
      - "34100"
    ports:
      - "34100:6379"
    command:
      - 'redis-server'
      - '--requirepass ${REDIS_PASSWORD}'
     - bla bla
```

If I ssh to my host and curl `http://localhost:12135` - it returns my webpage. However if I visit my website `mydomain.com ` in browser - I get 502 error.  

In logs of docker I see the following:

```
HTTPS-PORTAL v1.10.1
========================================

[cont-init.d] 00-welcome: exited 0.
[cont-init.d] 10-persist-env: executing...
[cont-init.d] 10-persist-env: exited 0.
[cont-init.d] 20-setup: executing...
DH parameters appear to be ok.
-----BEGIN DH PARAMETERS-----
bla
bla
bla
-----END DH PARAMETERS-----
RSA key ok
2020/03/25 12:07:37 [notice] 245#245: signal process started
2020/03/25 12:07:37 [notice] 248#248: signal process started
Signing skipped for mydomain.com, it expires at 63 days from now.
2020/03/25 12:07:37 [notice] 250#250: signal process started
2020/03/25 12:07:37 [notice] 252#252: signal process started
Signing skipped for www.mydomain.com, it expires at 63 days from now.
2020/03/25 12:07:38 [notice] 254#254: signal process started
[cont-init.d] 20-setup: exited 0.
[cont-init.d] 30-set-docker-gen-status: executing...
[cont-init.d] 30-set-docker-gen-status: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020/03/25 12:07:59 [error] 300#300: *1 connect() failed (111: Connection refused) while connecting to upstream, client: my_ip, server: www.mydomain.com, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:12135/", host: "www.mydomain.com"
```

Any advice how to fix it? Thanks!

**Comment by SteveLTN** [comment]
I don't understand what you are trying to do here:
> `DOMAINS: 'mydomain.com => mydomain.com, www. mydomain.com.com -> http://127.0.0.1:12135'`

**Comment by heyt0ny** [comment]
sorry copied it wrong. it's 
```
DOMAINS: 'mydomain.com => www.mydomain.com, www.mydomain.com -> http://127.0.0.1:12135'
```

**Comment by SteveLTN** [comment]
Aha, I think the reason is this:

127.0.0.1 is your docker host machine's IP address, from the machine. Since HTTPS-PORTAL runs in a docker container, it doesn't see the host machine as 127.0.0.1. Replace your `127.0.0.1` with `dockerhost` instead.

[See this section](https://github.com/SteveLTN/https-portal#hybrid-setup-with-non-dockerized-apps)
The document describes when your apps are not in docker. Your case is similar. Though it is in docker, but it's in a separate compose, and you try to access it through the port exposed on the host machine.

If you want to access it within docker, try to set up a `network` in your app's docker-compose.yml, and use the same in HTTPS-PORTAL. 

Alternatively just put PORTAL in the same compose file.

**Comment by heyt0ny** [comment]
Thanks, you are right. Created docker network `nginx-proxy`. Add added this to both docker-compose files:
```
networks:
    default:
       external:
         name: nginx-proxy
```

If I run `docker network inspect nginx-proxy`. It shows that all containers (website and website_https-portal_1) are on the same network:

```
[
    {
        "Name": "nginx-proxy",
        "Id": "e9a59dd9e78f64ff6b9b2b93741fa9b58504daf70b41c4dc927439ede38f12fb",
        "Created": "2020-03-25T16:40:50.172361677Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.27.0.0/16",
                    "Gateway": "172.27.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "1448b235aabe7b4acdfb8e04089cd71f39d8cd691b35e9f705fc0a2c47f9d9c6": {
                "Name": "redis",
                "EndpointID": "28f2db0f0ac8366c4c15df02c03479e2bc0befb02920a7e417569fd865988ffe",
                "MacAddress": "02:42:ac:1b:00:02",
                "IPv4Address": "172.27.0.2/16",
                "IPv6Address": ""
            },
            "821454f9aef97fbe6655e5fc91847e53272d31486bac84e81dfbd01f3ea481f3": {
                "Name": "website",
                "EndpointID": "9cb92ff7de793441aa55441630782c197e21c1d6920cdd6a8602d5c1197577b8",
                "MacAddress": "02:42:ac:1b:00:04",
                "IPv4Address": "172.27.0.4/16",
                "IPv6Address": ""
            },
            "9e46c1101879c8145f8fdd09aeebd377705ee5e96624b207f1fa9f267c5af9bc": {
                "Name": "api",
                "EndpointID": "81cd05f26ae7cf1972847fbd557bfd48451a6f4c700b02022a303e5517e52eb5",
                "MacAddress": "02:42:ac:1b:00:03",
                "IPv4Address": "172.27.0.3/16",
                "IPv6Address": ""
            },
            "e2d0e91fff095f7d578a58cb5d4336594bb5708a7b1a21661881da7975972946": {
                "Name": "website_https-portal_1",
                "EndpointID": "78f43ac55a268fd32d4194b7710f39a6b889436da10a05a1a1ebfc7f6f97ff7c",
                "MacAddress": "02:42:ac:1b:00:05",
                "IPv4Address": "172.27.0.5/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

But it's still 502 error 🤔
