### ISSUE TITLE
[Feature request] Allow HSTS configuration through environment variables

### ISSUE THREAD

**Issue by ijaureguialzo** [SteveLTN/https-portal#235]
Hello, would be possible to add two more variables to HSTS configuration? 

I'm trying to add a site to https://hstspreload.org and only the max-age parameter can be set in composer file.

It would be nice to be able to do something like:

```
HSTS_MAX_AGE: 31536000
HSTS_SUBDOMAINS: true
HSTS_PRELOAD: true
```

So the final header sent to the browser resulted in:

```
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

Thanks in advance.

**Comment by SteveLTN** [comment]
Sounds reasonable. I'll find some time.

**Comment by SteveLTN** [comment]
Hi, I published a new release `1.12.0`. It should be built shortly.

Since there are infinite amount of possible configurations and I can't create an environment variable for each of them, I took a different approach than you suggested. Check out [here](https://github.com/SteveLTN/https-portal#other-server-block-level-configurations).

It now support custom configurations of Nginx. For your need, you can remove `HSTS_MAX_AGE` in your docker-compose, and add:

```yaml
environment:
  CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
```

Hope you are happy with this.
