### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG Kubernetes/Apache deployment

### ISSUE THREAD

**Issue by jrcichra** [SteveLTN/https-portal#237]
I'm trying to set https-portal in front of an apache container inside Kubernetes. Here's my YAML so far for https-portal:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: https
  namespace: apache
  labels:
    app: https
spec:
  ports:
    - port: 80
      name: https-http
    - port: 443
      name: https-https
  selector:
    app: https
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apache
  name: https
  labels:
    app: https
spec:
  selector:
    matchLabels:
      app: https
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: https
    spec:
      containers:
      - image: steveltn/https-portal:1
        name: https
        ports:
        - containerPort: 80
          name: https-http
        - containerPort: 443
          name: https-https
        env:
          - name: DOMAINS
            value: "justins.domain.com -> http://apache:80"
          - name: ERROR_LOG
            value: "stdout"
          - name: ACCESS_LOG
            value: "stderr"
          - name: DEBUG
            value: "true"
          - name: FORCE_RENEW
            value: "true"
```
I've purposely censored my real domain name.

And for apache:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: apache
  labels:
    app: apache
spec:
  ports:
    - port: 80
  selector:
    app: apache
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pv-claim
  namespace: apache
  labels:
    app: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pv-claim-etc
  namespace: apache
  labels:
    app: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apache
  name: apache
  labels:
    app: apache
spec:
  selector:
    matchLabels:
      app: apache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: php:7.2-apache
        name: apache
        ports:
        - containerPort: 80
          name: apache
        volumeMounts:
        - name: apache-persistent-storage
          mountPath: /var/www/html
        - name: apache-persistent-storage-etc
          mountPath: /etc/apache2/
      volumes:
      - name: apache-persistent-storage
        persistentVolumeClaim:
          claimName: apache-pv-claim
      - name: apache-persistent-storage-etc
        persistentVolumeClaim:
          claimName: apache-pv-claim-etc
```

These both live in the same Kubernetes namespace of "apache", so pointing my domain to "apache:80" resolves properly.

Container logs for apache have nothing special, I'm not seeing them being accessed. Here's what I'm seeing in the https-portal container (400's coming back with noisey output):

```
\x22;s:4:\x22name\x22;s:3:\x22ads\x22;}554fcae493e564ee0dc75bdf2ebf94ca" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36" "-"
10.42.0.0 - - [28/Jul/2020:01:39:04 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03?\x80\xD7\x00\xE9/QN,5\xC6\x9FNmJy\xDF\xC0\x96e\x82\xD4y\x0E\xB5\xA7\xA9M" 400 150 "-" "-" "-"
10.42.0.0 - - [28/Jul/2020:01:39:04 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\xBA\x89\x9B\x9F*\xE5p \x83\x14\xE9\xE4'V\xB8\xF1\xA8\xF0\x14B}8\xB4\x11\xC5\x08{\xCE\xCA\x1ET8 \xB0l\xCD\x84\xC11?*\xE4\xED}u\xB1@\xFE\xA9\xEB9E\xC4\xBEzLo\xCC\x84" 400 150 "-" "-" "-"
10.42.0.0 - - [28/Jul/2020:01:39:04 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03l\x18\xA3\xE2/\xBAc\x8ERPz\x12!\x98\xC2" 400 150 "-" "-" "-"
10.42.0.0 - - [28/Jul/2020:01:39:04 +0000] "\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03y\xBE\xF4\xAF[e$4\xB4S\xA2X9KG\x88\xBD\x95\xEE2o\x01bS\xB2C\xA9\x04\xE0\xA7\xEEf ~\xFF \x13\x15\x7F\xEE\xED\xB4\x8C\x83\xF4Y\x96\x97\x10\xAF\xDA\x89\xBF\xEC\xAC\xDCMl6L<\xD0\xB6\x93\x99\x00\x22\xDA\xDA\x13\x01\x13\x02\x13\x03\xC0+\xC0/\xC0,\xC00\xCC\xA9\xCC\xA8\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x00" 400 150 "-" "-" "-"
```

Wireshark:

![image](https://user-images.githubusercontent.com/1342149/88609350-def8d800-d051-11ea-8daf-e7daab935d77.png)

I'm not sure why I'm getting a bad request back. Firefox says this:

```
Secure Connection Failed

An error occurred during a connection to justin.example.com. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

What am I missing?
