### ISSUE TITLE
NET::ERR_CERT_INVALID

### ISSUE THREAD

**Issue by sumanthratna** [SteveLTN/https-portal#251]
relevant parts of `docker-compose.prod.yml`:
```yml
version: '3.8'

services:
  django:
    expose:  # runs Gunicorn; serves HTTP on port 8000
      - 8000

  https-portal:
    image: steveltn/https-portal:1.15.0
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'live.hacktj.org.private -> http://django:8000'
      STAGE: 'local'  # {'local', 'staging', 'production'}  # can't use staging or production with .private TLD
      # WEBSOCKET: 'true'
      # LISTEN_IPV6: 'true'
      ERROR_LOG: stdout
      ACCESS_LOG: stderr
```

- `curl live.hacktj.org.private -L -k` returns the webpage, as expected
- `curl live.hacktj.org.private -L` returns:
```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

in Chrome, this is what I see:
> # Your connection is not private
> Attackers might be trying to steal your information from live.hacktj.org.private (for example, passwords, messages, or credit cards). 
> 
> NET::ERR_CERT_INVALID
> 
> When Google Chrome tried to connect to live.hacktj.org.private this time, the website sent back unusual and incorrect > credentials. This may happen when an attacker is trying to pretend to be live.hacktj.org.private, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.
> 
> You cannot visit live.hacktj.org.private right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

(I'm using dnsmasq)

---

do you know why `local` isn't working?
