### ISSUE TITLE
Private key generated on each restart

### ISSUE THREAD

**Issue by ijaureguialzo** [SteveLTN/https-portal#253]
Hello,

after today's update I've noticed that each time https-portal starts, a new key is generated for `default_server` host. 

I get this message on every startup:

```text
https-portal_1  | writing new private key to '/var/lib/https-portal/default_server/default_server.key'
```

Two files are created on every reboot: `default_server.key` and `default_server.crt`.

I'm running version 1.15.1 and this is the docker-compose config I use (it's split in two files, sorry):

```yaml
https-portal:
  image: steveltn/https-portal:${HTTPS_PORTAL_VERSION}
  environment:
    - CLIENT_MAX_BODY_SIZE=1024M
  volumes:
    - https-portal_certs:/var/lib/https-portal
    - https-portal_logs:/var/log/nginx
  ports:
    - 80:80
    - 443:443
```

```yaml
https-portal:
  restart: unless-stopped
  environment:
    DOMAINS: >
      test.com -> http://nginx:80,
      www.test.com => https://test.com,
      static.test.com,
      other.test.com -> http://other:80,
    STAGE: production
    CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
      add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    #FORCE_RENEW: 'true'
  volumes:
    - https-portal_static_sites:/var/www/vhosts
```

Is this the expected behaviour? How can I disable this key generation?

Thanks.
