### ISSUE TITLE
PHP-FPM/Fast-CGI Support

### ISSUE THREAD

**Issue by MaterialFuture** [SteveLTN/https-portal#277]
I'm able to get the wordpress site working on the base apache default but I cannot get the php-fpm implementation working even after adding the fastcgi params in the nginx config. I'm not sure what I'm missing, but is there support for php-fpm in https-portal and I'm just missing it?

My Dockerfile
```
version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - wp
    restart: always
    environment:
      DOMAINS: 'example.com -> http://wp:9000'
      STAGE: staging
    volumes:
      - ./public_html:/var/www/html
      - https-portal-data:/var/lib/https-portal
      - ./nginx-conf/example.site.com.ssl.conf:/var/lib/nginx-conf/example.site.com.ssl.conf.erb:ro
    networks:
      - app-network
  wp:
    build: .
    restart: always
    container_name: wp
    ports:
      - 9000:9000
    environment:
      WORDPRESS_DB_HOST: host:porst
      WORDPRESS_DB_NAME: name
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_TABLE_PREFIX: wp
    volumes:
      - ./public_html:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - app-network

volumes:
  wp:
  https-portal-data:

networks:
  app-network:
    driver: bridge
```

The names and values in the yml file were changed, with the correct values I'm able to get it working, but when I use the fpm version I get `recv() failed (104: Connection reset by peer) while reading response header from upstream`

I'm building the wordpress image from `wordpress:5.7.0-php7.4-fpm-alpine` in the Dockerfile along with some other custom configurations, which shouldn't affect nginx as far as I'm aware.

Thanks,
