### ISSUE TITLE
Headers sent with an underscore are not forwarded.

### ISSUE THREAD

**Issue by cooperfrench95** [SteveLTN/https-portal#289]
# Expected behaviour

All headers are forwarded as-is

# Actual behaviour

Send an http request with a header like `access_key` -> it will not be received by the server that https-portal is set to forward requests to.

Send an http request with a header like `accesskey` -> it will be received by the server that https-portal is set to forward requests to.

Version: latest

**Comment by SteveLTN** [comment]
Hi, according to [this article](https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/?highlight=disappearing%20http%20headers#missing-disappearing-http-headers):

> If you do not explicitly set `underscores_in_headers on;`, NGINX will silently drop HTTP headers with underscores (which are perfectly valid according to the HTTP standard). This is done in order to prevent ambiguities when mapping headers to CGI variables as both dashes and underscores are mapped to underscores during that process.

If you want to set the above-mentioned configuration flag, you can do:

```yaml
    environment:
      DOMAINS: > 
        example.com -> upstream
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: "underscores_in_headers on;"
```
