### ISSUE TITLE
example for wordpress does not work

### ISSUE THREAD

**Issue by chickencoding123** [SteveLTN/https-portal#303]
This is the `docker-compose.yml` suggested by the [home page]() but after running `docker-compose up -d`, there's nothing at https://wordpress.example.com and browser displays the standards web page not found.

```yaml
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    environment:
      DOMAINS: 'wordpress.example.com -> http://wordpress:80'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    volumes: 
      - https-portal-data:/var/lib/https-portal

  wordpress:
    image: wordpress
    links:
      - db:mysql

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '<a secure password>'

volumes:
  https-portal-data:
```
