### ISSUE TITLE
502 Bad Gateway when trying to redirect to a sample Nginx container

### ISSUE THREAD

**Issue by tommywalkie** [SteveLTN/https-portal#312]
Hi @SteveLTN , I successfully could test/deploy `https-portal` using stuff like Ghost CMS, Wordpress, or Strapi. But I still face a weird issue for simplier containers, like a default Nginx/Caddy one.

```yaml
version: '3.1'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - strapi
      - blog
    restart: always
    environment:
      DOMAINS: 'domain.com -> http://blog:8080, www.domain.com -> http://blog:8080, api.domain.com -> http://strapi:1337'
      STAGE: 'production'
    depends_on:
      - blog

  blog:
    image: nginx
    ports:
      - '8080:80'
  
  strapi:
    image: strapi/strapi
    # environment: ...
    volumes:
      - strapi-volume:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    # environment: ...
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  strapi-volume:
  postgres-volume:
```

I am able to reach the Nginx container welcome page through my IP address `:8080` but for some reason, `https-portal` can't redirect to it.
