### ISSUE TITLE
Logs are no longer output.

### ISSUE THREAD

**Issue by nrikiji** [SteveLTN/https-portal#313]
I keep a log of the proxy server container I created with http-portal.

After this log is output, the access log is no longer recorded.
```
Renewing ...
Renewal skipped for foo.bar, it expires at 31 days from now.
Renewal done.
```
Could you please let me know the cause of this and if there is a solution.

Also, here is my docker-compose.yml
```yaml
services:
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
        tag: http-portal/{{.Name}}/{{.ID}}
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: Asia/Tokyo
      STAGE: 'production' # Don't use production until staging works
      DOMAINS: >-
        foo.bar -> http://foo-bar-web:8000,
      CLIENT_MAX_BODY_SIZE: 10M
      ERROR_LOG: stdout
      ACCESS_LOG: stderr
    volumes:
      - https-portal-data:/var/lib/https-portal
    networks:
      - foo-bar-nw
    depends_on:
      - foo-bar-web
```

**Comment by SteveLTN** [comment]
Hi! This is interesting. Likely to be a bug. I need to look into it.

**Comment by nrikiji** [comment]
Thank you. I don't see this being discussed so far, but I guess others aren't bothered...

**Comment by SteveLTN** [comment]
Hi, I played around with my containers, but don't see a similar issue. I notice that you pu `ERROR_LOG: stdout` and `ACCESS_LOG: stderr`. I wonder if this will make a difference.

**Comment by nrikiji** [comment]
Thank you. I had copied here without much thought...
https://github.com/SteveLTN/https-portal/#logging-configuration

```
https-portal:
  # ...
  environment:
    ERROR_LOG: stderr
    ACCESS_LOG: stdout
```
Is this correct?
