### ISSUE TITLE
Access credentials - domain certificate fullchain and 

### ISSUE THREAD

**Issue by usystemsoftwares** [SteveLTN/https-portal#325]
Hello.

How i access credentials - 
 full chain domain certificate 
 domain private key 

I use volume to expose the file's credentials to other containers, but I didn't find those keys.

I found account.key and dhparam.pem inside the root of the certificates and chained.crt, domain.csr, domain.key and signed.crt inside the URL > production

```
 https-portal:
    image: steveltn/https-portal:1
    volumes:
      - "/data/ssl_certs:/var/lib/https-portal"
      - "./certificates/:/var/lib/https-portal"
      - "https-portal-data:/var/lib/https-portal"
    ports:
      - 80:80
      - 443:443
    links:
      - nest
    restart: always
    environment:
      DOMAINS: XXX
      STAGE: 'production'
      FORCE_RENEW: 'false'
    networks:
      - network

```
