### ISSUE TITLE
Configure https-portal and Streamlit - web app

### ISSUE THREAD

**Issue by dan-adi** [SteveLTN/https-portal#332]
Hello,
I am having trouble configuring https-portal to work with a Streamlit web app deployed with docker.
This is my attempt at a docker-compose.yaml:
```
version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - streamlit_app
    restart: always
    environment:
      WEBSOCKET: 'true'
      DOMAINS: 'http://example.go.ro/ -> http://streamlit_app:8501'
      STAGE: production # mantenha em staging até o total funcionamento
    volumes:
      - https-portal-data:/var/lib/https-portal
      
  streamlit_app:
    build:
      dockerfile: ./Dockerfile
      context: ./ 
    volumes:
      - .:/ETCWebApp
    ports:
      - 8501:8501
    restart: always
```
On my router I have the external ports 80,443 forwarded to internal 8501 port.
Using the docker-compose up, I get no errors, but I can only access my webapp on HTTP not HTTPS.
Any ideas how to make it work?
Thank you

**Comment by dan-adi** [comment]
This is the error it gives:
```
Failed to sign clearskies.go.ro.
https-portal_1   | Make sure your DNS is configured correctly and is propagated to this host
https-portal_1   | machine. Sometimes that takes a while.
```
Any idea how to solve it?

**Comment by gerold-penz** [comment]
Hi!

1.) I think, your docker-compose.yaml should look so:

```
services:

  streamlit_app:
    build:
      dockerfile: ./Dockerfile
      context: ./ 
    volumes:
      - .:/ETCWebApp
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1.22
    depends_on:
      - streamlit_app
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment:
      WEBSOCKET: 'true'
      DOMAINS: 'example.go.ro -> streamlit_app:8501'
      STAGE: production # mantenha em staging até o total funcionamento
    volumes:
      - https-portal-data:/var/lib/https-portal
      
```

2.) Your router must forward the ports 80 and 443 to your computer, directly. Not the Port 8501.
```
80 --> 80
443 --> 443
```

Maybe it helps.
