### ISSUE TITLE
Multiple Apps support

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [SteveLTN/https-portal#335]
@SteveLTN 

Can we add more containers in the same host, something like modifying the ports (9443 instead of 443, 9080 instead of 80)

Like below:

Default Container:

```yml
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
     - '80:80'
     - '443:443'
    environment:
      DOMAINS: 'test.domain.in -> 10.20.3.1:8111'
      STAGE: 'staging' # Don't use production until staging works
      WEBSOCKET: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
    https-portal-data: {}# Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
```

Additional Container:

```yml
version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
     - '9080:80'
     - '9443:443'
    environment:
      DOMAINS: 'test.domain.in -> 10.20.3.1:8222'
      STAGE: 'staging' # Don't use production until staging works
      WEBSOCKET: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
    https-portal-data: {}# Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
```

is this ok, or we will face any issues in the future while updating the certs, etc?
