### ISSUE TITLE
feature request: multi-line domain environment variable

### ISSUE THREAD

**Issue by rogervdf** [SteveLTN/https-portal#349]
Thank you for this repo @SteveLTN we use it for quite a lot of services in production

Right now the package chokes on multi-line environmental variables, which docker-compose supports with `|-` 

```
version: '3.7'

services:

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: |-
        'domain1.systems -> http://container1:80,
        domain2.xyz -> http://container2:80'
```

The error specifically:

`https-portal_1   | Error: Invalid descriptor` `domain1.systems -> container1:80`

It seems the parsing doesn't like when it is being passed the multi-line

Would you be able to add multi-line support on the domain environment variable? It would make using your package for large numbers of domains easier to maintain; scrolling up and down a long line to find the right domain and container takes time.
