### ISSUE TITLE
Certificate chain incomplete / untrusted on iOS 9 Safari?

### ISSUE THREAD

**Issue by aforty** [SteveLTN/https-portal#35]
Hi,
I've setup a few sites through https-portal, one static and one using automatic container discovery. Both exhibit the same problems, both are untrusted by Safari in iOS 9 (desktop browsers are fine). When I run a test (https://www.ssllabs.com/ssltest/analyze.html) on the static site, I get the following warning: 

**This server's certificate chain is incomplete.**

Here's my configuration:
```
https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./vhosts:/var/www/vhosts
  restart: always
  environment:
    PRODUCTION: 'true'
    FORCE_RENEW: 'true'
    CLIENT_MAX_BODY_SIZE: 600M
    GZIP: 'on'
    PROXY_READ_TIMEOUT: 900
    DOMAINS: '__domain_hidden__'
```

Full report attached.

[SSL Server Test.pdf](https://github.com/SteveLTN/https-portal/files/198021/SSL.Server.Test.pdf)
