### ISSUE TITLE
StreamingHttpResponse Not work over https

### ISSUE THREAD

**Issue by maycuatroi** [SteveLTN/https-portal#354]
I'm currently facing an issue with using HTTPS with the following configuration:

```yaml
https-portal:
  image: steveltn/https-portal:1
  ports:
    - "80:80"
    - "443:443"
  environment:
    DOMAINS: 'xxx.xxx.tech -> http://django:8080'
    STAGE: 'production'  # Don't use production until staging works
    FORCE_RENEW: true
    EMAIL: 'xxx@xxx.com'
```

When sending requests through the server, the Stream Response seems to not work:

```python
return StreamingHttpResponse(
            streaming_content=stream, content_type="text/event-stream"
        ) # not working
```

However, when I test with the same server, bypassing HTTPS and directly opening the container's `django` port to send an HTTP request to port 8080, the stream response works fine.

I have limited experience handling Stream Responses with NGINX and would appreciate any guidance.

![image](https://github.com/SteveLTN/https-portal/assets/5876946/3797e219-ed2a-4258-b0d9-a143fe8aeea0)
