### ISSUE TITLE
can't create Thread: Operation not permitted

### ISSUE THREAD

**Issue by Zenoo** [SteveLTN/https-portal#368]
Hello,

I'm getting this error while running https-portal:

![Image](https://github.com/user-attachments/assets/b866be63-1107-4bdc-a9ed-fd2b8641b205)

Here is the docker compose service config used:

```yml
https-portal:
     image: steveltn/https-portal:1
     depends_on:
       - server
     ports:
       - 80:80
       - 443:443
     restart: always
     #
     # Save our SSL certs between runs so they aren't regenerated on every single run.
     #
     volumes:
       - ./ssl_certs:/var/lib/https-portal
     environment:
       DOMAINS: 'xxxxxx.xxxxxx.com -> http://server:8000 #production, xxxxxxx.xxxxxxxxx.com -> http://server:8080 #production'
       STAGE: 'production'
       PROXY_CONNECT_TIMEOUT: 180
       PROXY_SEND_TIMEOUT: 180
       PROXY_READ_TIMEOUT: 180
       KEEPALIVE_TIMEOUT: 185
       # FORCE_RENEW: 'true'
       #
       # Allow larger files to be uploaded
       #
       CLIENT_MAX_BODY_SIZE: 64M
```
