### ISSUE TITLE
Use https-portal as a proxy for host running directly on the host outside docker

### ISSUE THREAD

**Issue by damascene** [SteveLTN/https-portal#373]
Is it possible to have a domain that is connected to a port in the host instead of a docker container? 

Example:

```
https-portal:
  # ...
  environment:
    DOMAINS: 'wordpress.example.com -> http://wordpress:80, another_domain.example.com -> http://127.0.0.1:8118'

```

So the second domain would be an app running on the host machine. I saw some suggestions to use `host.docker.internal` but it didn't work in my case. 

Any suggestions please?
