### ISSUE TITLE
Caching not working.

### ISSUE THREAD

**Issue by ddulic** [SteveLTN/https-portal#44]
Caching seems to not be working. Also tried adding `Gzip: 'on'`. Didn't fix the issue.

[Check GZIP Compression](http://checkgzipcompression.com/?url=http%3A%2F%2Fdamir.tech)

**Comment by SteveLTN** [comment]
Can you provide more information?

**Comment by ddulic** [comment]
Sure. I was noticing slower load times on my website so I did a few checks. And it seems that gzip isn't enabled on the nginx side. This is my .yml code:

```
https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  links:
    - web
  restart: always
  environment:
    DOMAINS: 'damir.tech -> http://web, cv.damir.tech'
    CLIENT_MAX_BODY_SIZE: '10M'
    GZIP: 'on'
    STAGE: 'production'
   # FORCE_RENEW: 'true'
  volumes:
    - /data/https-portal/vhosts:/var/www/vhosts
web:
  image: wordpress
  links:
    - db:mysql
  volumes:
    - ~/wordpress/wp_html:/var/www/html
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 'W9ghNcBxBubu3B4gAT'
```
I think you need to add `gzip_types` in the nginx.conf in order to fully utilise the compression.
