### ISSUE TITLE
wordpress example - always failing on verification step

### ISSUE THREAD

**Issue by white-hat** [SteveLTN/https-portal#45]
Hello!
I have a domain at Route53 and I'm trying to install an https proxy by your guide.
The only 2 strings I've changed - the domain name and mysql password.
Everything else - same as in your example.
I tried with digital ocean and EC2, different subdomains, but I always get same error:
```
ValueError: Wrote file to /var/www/default/challenges/g_1gc6VVSosIaplaaiPbp0I6RBSznMPsNpFKtbN8uNc, but couldn't download http://testme.afdevops.com/.well-known/acme-challenge/g_1gc6VVSosIaplaaiPbp0I6RBSznMPsNpFKtbN8uNc
```
I logged in a container - /var/www/default/challenges is empty. 
If I create hello.html file there, I can reach it by URL http://testme.afdevops.com/.well-known/acme-challenge/hello.html
So I guess the problem is not in nginx.

```
# cat docker-compose.yml
https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  links:
    - wordpress
  restart: always
  environment:
    DOMAINS: 'testme.afdevops.com -> http://wordpress'
    # STAGE: 'production'
    # FORCE_RENEW: 'true'

wordpress:
  image: wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: supersecretpassword 
```
