### ISSUE TITLE
connection is not secure/trusted in Firefox, Chrome, and Safari browsers

### ISSUE THREAD

**Issue by rcholic** [SteveLTN/https-portal#53]
First of all, thanks for making this great docker image that uses lets encrypt for generating SSL certificates. I've tried this and my `https` seems to be working fine with this docker image. The following is my docker-compose, but all three browsers I tested still show unstructed/insecure connection. I am not sure if this is related to this `https-portal` or the certificates generated by letsencrypt is not trusted:

```
nginx_portal:
   image: steveltn/https-portal
   container_name: nginx_proxy_container
   ports:
    - "80:80"
    - "443:443"
   volumes:
    - ./ssl_letsen:/var/lib/https-portal
    - /var/run/docker.sock:/tmp/docker.sock:ro
   environment:
    DOMAINS: 'www.domain.com -> http://api:1337'
```

Visiting https://www.domain.com, I got warnings in my browsers. Any ideas what might be wrong? Thanks!
