### ISSUE TITLE
*101 connect() failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by kampta** [SteveLTN/https-portal#59]
I am using this kind of setup for my webapp - https://github.com/kampta/https-portal-example
It had been working fine for last one month or so but has starting throwing `error 502` recently. Here is what I see in the log.

```
nginx_1       | 2016/08/04 14:29:15 [error] 159#159: *101 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: example.com, request: "GET / HTTP/1.1", upstream: "http://xx.xx.xx.xx:8000/", host: "example.com"
nginx_1       | 2016/08/04 14:29:16 [error] 159#159: *101 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://xx.xx.xx.xx:8000/favicon.ico", host: "example.com", referrer: "https://example.com/"
```

On googling, it seems to have something to do with ipv4/ipv6. Ideas? (Thanks a lot in advance)

**Comment by kampta** [comment]
Think I know when the problem started appearing.  I made changes to the `docker-compose.yml` so that it looks like this

```
app:
  restart: always
  build: ./app
  expose:
    - "8000"
  links:
    - redis
  environment:
    STAGE: production
  command: /usr/local/bin/gunicorn --workers=2 --bind :8000 run:application

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - app
  links:
    - app:app
  environment:
    DOMAINS: 'example.com -> http://app:8000'
    STAGE: production

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
```
Issue #12 kinda look at the same problem. Any ideas on how to fix this?

**Comment by kampta** [comment]
I solved the issue by adding links to the `nginx` service

```
nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - app
  links:
    - app:app
    - redis:redis
```

Not exactly sure how, but this seems to solve the problem. Thanks
