### ISSUE TITLE
Default redirections are made to http

### ISSUE THREAD

**Issue by fathzer** [SteveLTN/https-portal#67]
Hello,

First of all, I'm a newbie, please be indulgent if my question is stupid ...

I run https-portal in front of a php-apache container. Everything works fine, except the default http redirections that are made to http instead of https. For instance, let say we have a directory named test in our website. Calling https://mysite.com/test returns a 301 code with redirection to **http**://mysite.com/test/.
This is not the same behaviour we obtain using a pure apache-php server with https enabled. In such a case, apache returns a 301 code with redirection to **https**://mysite.com/test/.
The problem is some http clients (ie java HttpURLConnection) follows redirection only if the scheme isn't changed, for security concerns.
Finally, my question: Is it possible to obtain the same behavior as pure apache-php server (redirection to https)?

Here is my docker-compose file:
```
version: '2'
services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - test
    restart: always
    environment:
      DOMAINS: 'test.fathzer.com -> http://test #production'
    volumes:
      - /root/ssl_certs:/var/lib/https-portal

  test:
    image:
      php:5-apache
    volumes:
      - /home/test/www:/var/www/html
    restart: always
```

I've made 2 web sites to make the demonstration:
One powered by https-portal: https://test.fathzer.com/test -> Redirects to http
One with plain old apache-php server: https://test2.fathzer.com/test -> Redirects to https

Best regards,
PS: Thanks for that great project :-)
