### ISSUE TITLE
Container auto discovery vhost not found

### ISSUE THREAD

**Issue by vabue** [SteveLTN/https-portal#69]
Hi!  Thank you for amazing project. 

I've encountered into some strange issue with autodiscovery:

```
https-portal_1  | 2016/11/06 18:37:17 
[error] 170#170: *2 "/var/www/vhosts/stilo.com.ua/index.html" is not found 
(2: No such file or directory), 
client: 77.213.32.33, server: stilo.com.ua, request: "GET / HTTP/1.1", 
host: "stilo.com.ua"
```

If I setup container with upstream - everything works perfectly.  I thought that it is redmine issue, but I get the same error if I try to autodiscover container with basic webserver setup and different domain name.

Here is my docker-compose.yml:

```
  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - redmine
    restart: always
    environment:
      #DOMAINS: 'stilo.com.ua -> http://redmine'
      STAGE: 'production'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  redmine:
    image: sameersbn/redmine
    container_name: redmine
    ports:
     - "8081:80"
    volumes:
     - /opt/redmine/data:/home/redmine/data
    environment:
     - DB_HOST=mydbip
     - DB_NAME=mysqluser
     - DB_USER=mybase
     - DB_PASS=mypass
     - DB_TYPE=mysql
     - SMTP_METHOD=async_smtp
     - SMTP_USER=mail@mymail.com
     - SMTP_PASS=mypass
     - NGINX_MAX_UPLOAD_SIZE=200m
     - REDMINE_HTTPS=true
     - REDMINE_SECRET_TOKEN=mysecret
     - VIRTUAL_HOST=stilo.com.ua
     - VIRTUAL_PORT=8081
```
