### ISSUE TITLE
dockerhost redirection not working on Mac

### ISSUE THREAD

**Issue by athyuttamre** [SteveLTN/https-portal#72]
I'm trying to run the proxy locally and point it to an app running on my host machine (my Mac laptop running macOS Sierra.) Unfortunately I only get a "502 Bad Gateway" error.

Repro:

1. Create this `docker-compose.yml` file:

```
version: '2'
services:
  proxy:
    image: steveltn/https-portal
    ports:
    - 80:80    # HTTP on 80
    - 3000:443 # HTTPS on 3000 to allow SAML to work
    environment:
      STAGE: local
      DOMAINS: 'local.cis-dev.brown.edu -> http://dockerhost:8080'
```

2. Add `local.cis-dev.brown.edu` to your `/etc/hosts` like so:

```
127.0.0.1	local.cis-dev.brown.edu
```

3. Run `docker-compose up` to run the proxy.
4. Run `python -m SimpleHTTPServer 8080` from a directory with a simple `index.html`.
5. Navigate to `https://local.cis-dev.brown.edu:3000`. Expected to see the Python server, but actually receiving "502 Bad Gateway" error.

Any clue how to fix this?
