### ISSUE TITLE
Separate containers

### ISSUE THREAD

**Issue by wolfgang42** [SteveLTN/https-portal#79]
`nginx-proxy` supports [separate containers](https://github.com/jwilder/nginx-proxy#separate-containers) for the config generator and nginx, so the docker socket doesn't have to be bound to a publicly exposed container. I'd like to be able to do the same thing with `https-portal`, but it doesn't seem to be supported at the moment. What would it take to implement this? I took a look at the code and *mostly* understand what it's doing, but pointers would be appreciated.

**Comment by SteveLTN** [comment]
Hi, HTTPS-PORTAL's purpose is to create a simple solution for HTTPS sites. Being compatible with Nginx-proxy is not its goal. With that said, this is an interesting idea. I would accept pull-requests for that.

I guess the key is to start a separate docker-gen container which takes the template and make Nginx to receive reload signal when the config file is updated.

It could get messy, but should be doable.

**Comment by wolfgang42** [comment]
I had a go at this in commit wolfgang42/https-portal@ab0e8c8a08140f8e1d34dde6d701014c3aa40e9d. This is most definitely not ready for a PR.

I've heavily commented that commit, but here's the summary:
I hacked up the image so it now works with a separate `nginx` container but *not* as a self-contained standalone container. I couldn't get vanilla `jwilder/docker-gen` to work because it also needs to handle certificate creation and renewal. Instead, I took the `https-portal` image and pulled nginx out of it, replacing it with some extra volumes and a cross-container call to `nginx -s reload`.

Here's a `docker-compose.yml` which demonstrates usage:
```yaml
version: '2'
volumes:
  https-portal-certs: {}
  https-portal-www: {}
  https-portal-conf: {}
services:
  https-portal:
    image: https-portal-separate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - https-portal-certs:/var/lib/https-portal
      - https-portal-www:/var/www
      - https-portal-conf:/etc/nginx
    environment:
      NGINX_CONTAINER: https-portal-nginx
    network_mode: host # Workaround for /etc/hosts; probably not needed on most systems
  nginx:
    container_name: https-portal-nginx
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - https-portal-certs:/var/lib/https-portal:ro
      - https-portal-www:/var/www:ro
      - https-portal-conf:/etc/nginx:ro
    network_mode: host # Workaround for /etc/hosts; probably not needed on most systems
```
The main points to note here are the volumes used to share files between the containers, and the addition of the `NGINX_CONTAINER` environment variable, used to tell `https-portal` which container it should send reloads to.

Do you have any suggestions or advice? Is there a better approach to this? Is there anything I might have missed? Let me know if there's anything I can clarify, I don't feel like I've done a particularly good job explaining all of this.
