### ISSUE TITLE
MySQL Connection Refused

### ISSUE THREAD

**Issue by ddulic** [SteveLTN/https-portal#81]
Pulling the latest MariaDB Image results in:

Warning: mysqli::mysqli(): (HY000/2002): Connection refused in - on line 19

**Comment by SteveLTN** [comment]
I'll have look tonight.

**Comment by SteveLTN** [comment]
Hmm, what exact problem are you facing? MySQL is not the scope of HTTPS-PORTAL. If you encounter an error when running one of the examples, please tell me which one.

**Comment by ddulic** [comment]
Well specifically I have a problem with using your config (a bit modified)
```
https-portal:
  image: steveltn/https-portal
  ports:
    - '80:80'
    - '443:443'
  links:
    - web
  restart: always
  environment:
    DOMAINS: 'damir.tech -> http://web, dipl.damir.tech -> http://139.59.209.202, cv.damir.tech, do.damir.tech'
   # CLIENT_MAX_BODY_SIZE: '64M'
    GZIP: 'on'
    STAGE: 'production'
   # FORCE_RENEW: 'true'
  volumes:
    - /data/https-portal/vhosts:/var/www/vhosts
web:
  image: wordpress
  links:
    - db:mysql
  volumes:
    - ~/wordpress/wp_html:/var/www/html
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 'nopenopenope'
```
Nothing was drastically changed. Running 

- Ubuntu 16.04
- Docker version 1.12.3, build 6b644ec

Doing `docker-compose pull` or updating to the latest docker breaks everything. The first error when doing `docker-compose up` on this config results in the error given. The only thing where I can see MySQL used is within Wordpress, but the container is configured to use MariaDB if I understood the configuration correctly.
