### ISSUE TITLE
Path mapping

### ISSUE THREAD

**Issue by Vad1mo** [SteveLTN/https-portal#82]
I have two services **Web** and **API** that should be reachable on the same domain. 

app.corp.com/* --> Web
app.corp.com/v2/token --> Web
app.corp.com/v2/webhook --> Web
app.corp.com/v2/* --> API

Would it be possible to accomplish this with the https-portal and can you maybe quickly outline a path? As currently I don't see any way to do so.

**Comment by SteveLTN** [comment]
No. If Web and API are two machines you need to set up your own proxy, or customize Nginx config.

**Comment by Vad1mo** [comment]
Yes Web and API are two different container. 

If I use [this ](https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.ssl.conf.erb) template as the foundation and add path filtering in nginx , will something like this still work?
```
https-portal:
  # ...
  environment:
    DOMAINS: 'app.corp.com -> http://web, app.corp.com -> http://api'
````
Because in my cases both domains should point to different services.
