### ISSUE TITLE
HTTPS server in the "backend" container seems to only get HTTP requests forwarded

### ISSUE THREAD

**Issue by mkonersmann** [SteveLTN/https-portal#83]
I just wanted to witch from jwilder/nginx-proxy to https-portal for using let's encrypt in my installation with the Automatic Container Discovery scenario. It works flawlessly for all my services but gitlab.

The error message that comes from nginx in my browser is:
```400 Bad Request, The plain HTTP request was sent to HTTPS port```

Here is my docker-compose file (the hostname is changed here), which worked under jwilder/nginx-proxy.
```
gitlab:
   container_name: gitlab
   image: gitlab/gitlab-ce:latest
   hostname: gitlab.example.org
   expose:
      - 443
   ports:
      - "22:22"
   environment:
      - VIRTUAL_HOST= gitlab.example.org
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
   volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab:rw
      - ./data:/var/opt/gitlab:rw
   restart: always
```

I tried to remove or change VIRTUAL_PORT and VIRTUAL_PROTO to 80 and http respectively, but that did not fix anything. These environment variables were used by jwilder/nginx-proxy. I don't think they are used by https-portal, are they?

In the https-portal container logs I just see ```GET / HTTP/1.1" 400 264 "-" blah blah```

Is there an issue with forwarding https requests to the https server of gitlab?
