### ISSUE TITLE
docker-compose scale doesn't work

### ISSUE THREAD

**Issue by thomas15v** [SteveLTN/https-portal#84]
```yml
version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  odoo:
    build: .
    links:
      - db
    volumes:
      - .:/etc/odoo
      - ./third:/mnt/repo/third
      - ./custom:/mnt/repo/custom
      - odoo_file_store:/var/lib/odoo
    environment:
      - DEFAULT_HOST=192.168.137.128
      - VIRTUAL_PORT=8069
  web_proxy:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    links:
      - odoo
    environment:
      DOMAINS: 'odoo.client.be -> http://odoo:8069'
      STAGE: 'local'
      CLIENT_MAX_BODY_SIZE: '0'
    restart: always
volumes:
  odoo_file_store: {}
````

I use the following docker-compose file and scaling odoo doesn't route requests to other odoo instances. Taking odoo_1 down causes 504 time-out.
