### ISSUE TITLE
How to know that the renewal process is working?

### ISSUE THREAD

**Issue by kaplas** [SteveLTN/https-portal#86]
Hi there,

I set up my `https-portal` installation in Nov 2016. Now by accident, I noticed that my certificates were about to expire in 6 days. So the renewal process has not worked properly.

Before attempting to actually fix the situation, I tried to look for some clues from `docker logs` on what has (or has not) happened, but couldn't find anything meaningful from there.

The only thing related to cron was this line, from the start of the service:
```
Starting crond ...
```

Nothing else related to signing or anything. As there hasn't been any other issues related to the renewals not working, this might also be a Stupid User Error. I restarted the services quite many times when setting those up, so it might very well that I've used `STAGE: local`by accident or something. As I found no clues on what could be wrong, I just fixed the problem by `stop`ping and `up`ping the `https-portal`. This signed the certificates, and I'm good to go for the next three months.

However, to the actual questions:

1. How can I know that the renewal process and the cron job is working? Should there be some logs which I can check that the need for renewal has been checked? If not, could those be added? Could this information be added to the `README.md` as well?
2. If I do have some actual problem with my container, what should I check for? My `docker-compose` config for `https-portal` is like this (with the actual domain names removed):

```
https-portal:
  image: steveltn/https-portal
  container_name: https-portal
  restart: always
  ports:
    - 80:80
    - 443:443
  links:
    - foobar
  volumes:
    - ../apps/landing:/var/www/vhosts/my.first.domain
  environment:
    STAGE: production
    DOMAINS: >
      my.first.domain,
      my.second.domain -> http://foobar
```

Thank you for the help already in advance :)
