### ISSUE TITLE
Container stop automatically  (fail at starting nginx)

### ISSUE THREAD

**Issue by ynarish** [SteveLTN/https-portal#87]
Hi, I'm trying to run a simple container according to the [guide](https://github.com/SteveLTN/https-portal#quick-start), but the container stops automatically on CentOS 7.3.

docker-compose.yml
> https-portal:
>   image: steveltn/https-portal:latest
>   ports:
>     - '80:80'
>     - '443:443'
>   environment:
>     STAGE: local
>     DOMAINS: 'test.mysite.com'

\# docker-compose up
> ...
> https-portal_1  | Starting crond ...
> https-portal_1  | nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
> https-portal_1  | 2017/03/22 11:10:06 [emerg] 162#162: open() "/var/log/nginx/error.log" failed (2: No such file or directory)
> https-portal_1  | [cont-finish.d] executing container finish scripts...
> https-portal_1  | [cont-finish.d] done.
> https-portal_1  | [s6-finish] syncing disks.
> https-portal_1  | [s6-finish] sending all processes the TERM signal.
> https-portal_1  | [s6-finish] sending all processes the KILL signal and exiting.
> httpsportal_https-portal_1 exited with code 0

It seems to fail to start nginx. What should I do ?

**Comment by SteveLTN** [comment]
Tried with exactly same compose. Can you put up more logs?

```
https-portal:
  image: steveltn/https-portal:latest
  ports:
    - '80:80'
    - '443:443'
  environment:
    STAGE: local
    DOMAINS: 'test.mysite.com'
```
