### ISSUE TITLE
Missing host in nginx config

### ISSUE THREAD

**Issue by gdbjohnson** [SteveLTN/https-portal#94]
Hi there, 

With version 2 of Compose, I'm finding that I'm getting an error in the generated NGINX config... it is missing the hostname in the proxy_pass line.

Error:

```
https-portal_1  | 2017/05/06 21:04:58 [reconfig]: 2017/05/06 21:04:58 [emerg] 187#187: no host in upstream ":80" in /etc/nginx/conf.d/example.com.ssl.conf:18
https-portal_1  | 2017/05/06 21:04:58 [reconfig]: nginx: [emerg] no host in upstream ":80" in /etc/nginx/conf.d/example.com.ssl.conf:18
```

Generated config (inside container):

```
   location / {
        proxy_pass http://:80;   # <--- Missing host?
       ...
   }
```

My compose file:

```
version: "2"

networks:
  mynetwork:
    external:
      name: backend

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      STAGE: 'production'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default: {}
      mynetwork:
        aliases:
          - https-portal

```

I think it's related to this issue:

https://github.com/jwilder/nginx-proxy/issues/353
